# Generated by Django 2.2.7 on 2019-11-22 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='no_views',
        ),
        migrations.AddField(
            model_name='thread',
            name='no_views',
            field=models.IntegerField(blank=True, default=0, verbose_name='Views count'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='forum.Usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_image/default_profileImage.jpg', upload_to='profile_image'),
        ),
    ]
